### ISSUE TITLE
Elasticsearch connection

### ISSUE THREAD

**Issue by MLOpsWC** [maddevsio/aws-eks-base#229]
This modules works well and I have some question.
I'm focusing on the ELK stack and it was successfully deployed on EKS cluster.
The [Kibana](https://kibana-dev.leapturesearch.com) works well: https://kibana-dev.leapturesearch.com
My goal is to  connect to Elasticsearch using python3 and interact for creating index and search.
But I have some issue and have spent 5 days to fix that.
This could be a poor question, but kindly want to get help.

>from elasticsearch import Elasticsearch
>es = Elasticsearch('https://elasticsearch-master:9200', use_ssl=True)
>resp = es.info()

I want to know if my goal or the host is wrong.
Thank you.

**Comment by halfb00t** [comment]
Hi @MLOpsWC, thank you for you question!

Where are you trying to connect to Elasticsearch from - from within the cluster or from the outside?

If it's the first case and you are trying to connect from within the cluster - maybe the error is due to using self-signed ssl certificates for ELK, try to run you script with `PYTHONHTTPSVERIFY=0` to check this.

In the second case - It's impossible to connect to Elasticsearch from the Internet in the current configuration. By default Elasticsearch service is running enternally with `type=ClusterIP`, you need to change the type to `LoadBalancer` and protect its AWS LoadBalacner with security group.
